#TODO: Decidir se vai utilizar o GRPC ou se vai ser dividido com o mountpath ou ainda com o multirouter express example
version: '3.9'
services:
  simple-system:    
    container_name: simple-system
    image: node:lts-buster
    ports:
      - "3000:${API_GATEWAY_PORT}"
    env_file:
      - .env
    working_dir: /home/node/simple-system
    volumes:
      - ./:/home/node/simple-system
    command: sh -c "npm install && npm run start"
    depends_on:
      - mongo-database

  mongo-database:
    container_name: mongo-database
    image: mongo:latest
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_USER_PASSWORD}