#TODO: Decidir se vai utilizar o GRPC ou se vai ser dividido com o mountpath ou ainda com o multirouter express example
version: '3.9'
services:
  simple-system:    
    container_name: simple-system
    image: node:lts-buster
    ports:
      - "3000:${API_GATEWAY_PORT}"
    env_file:
      - .env
    working_dir: /home/node/simple-system
    volumes:
      - ./:/home/node/simple-system
    command: sh -c "cd authentication &&
      npm install &&
      cd ../ &&
      cd api-gateway &&
      npm install &&
      npm run start"